matrix:
  include:
  - python: "2.7"
    services: docker
    sudo: required
  - python: "3.4"
    services: docker
    sudo: required
  - python: "3.5"
    services: docker
    sudo: required
    env: BUILD_DOCS=yes

before_install:
  # openshift
  - sudo apt-get wget -y
  - wget https://github.com/openshift/origin/releases/download/v1.4.1/openshift-origin-client-tools-v1.4.1-3f9807a-linux-64bit.tar.gz -O /tmp/oc.tar.gz
  - mkdir /tmp/ocdir && cd /tmp/ocdir && tar -xvvf /tmp/oc.tar.gz
  - sudo mv /tmp/ocdir/*/oc /usr/bin/
  # - export GOPATH=/usr && go get github.com/kubernetes-incubator/kompose
  
# install:
#   - sudo make install

# before_script:
#   - sudo make syntax-check

# script:
#   # run tests
#   - make test
#   - make integration-test
#   - bash script/pushdocs.sh
